/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.uas.cadangan;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author str5
 */
public class mahasantri extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form mahasantri
     */
    public mahasantri() {
        initComponents();
//        this.componentForm("nim");
        tampilData();
        tabelMhs.setEnabled(false);
    }

    public void tampilData() {
        model = new DefaultTableModel();
        tabelMhs.setModel(model);
        model.addColumn("NIM");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("No. Kamar");
        model.addColumn("Jurusan");
        getData();
    }

    public void getData() {
        try {
            Statement stat = (Statement) conect.konekdb().createStatement();
            String sql = "Select * from menumahasantri";
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                Object[] obj = new Object[4];
                obj[0] = res.getString("nim");
                obj[1] = res.getString("nama");
                obj[2] = res.getString("nokamar");
                obj[3] = res.getString("jurusan");

                model.addRow(obj);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtkamar = new javax.swing.JTextField();
        txtjurusan = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        pw = new javax.swing.JTextField();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btcari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcarimhs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMhs = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bttambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("NIM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("NO. KAMAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JURUSAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, -1, -1));
        jPanel1.add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 235, -1));
        jPanel1.add(txtkamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 260, 46, -1));
        jPanel1.add(txtjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 141, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 235, -1));
        jPanel1.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 235, -1));

        btedit.setText("Edit");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        jPanel1.add(btedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 80, -1));

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        jPanel1.add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 80, -1));

        btcari.setText("Cari");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        jPanel1.add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 500, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bebas Neue Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("NAMA MAHASANTRI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, 20));
        jPanel1.add(txtcarimhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 530, -1));

        tabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMhs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 710, 110));

        jLabel11.setFont(new java.awt.Font("Bebas Neue Bold", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SANKSI");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, 50));

        jLabel12.setFont(new java.awt.Font("Bebas Neue Bold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DIVISI");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 414, -1, 50));

        jLabel13.setFont(new java.awt.Font("Bebas Neue Bold", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IQOB");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 514, -1, 50));

        jLabel14.setFont(new java.awt.Font("Bebas Neue Bold", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("MAHASANTRI");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 614, -1, 30));

        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        jPanel1.add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/uas/cadangan/newpackage/Copy of Salsa Dance Night Poster - Made with PosterMyWall (3).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed

        String carimhsValue = txtcarimhs.getText();
        try {
            Connection conn = (Connection) conect.konekdb();
            Statement stmt = conn.createStatement();
            ResultSet result = stmt.executeQuery("Select * from menumahasantri"
                    + " WHERE nama ='" + carimhsValue + "'");
            if (result.next()) {
                String namaResult = result.getString("nama");
                String nimResult = result.getString("nim");
                String passResult = result.getString("pass");
                String jurusanResult = result.getString("jurusan");
                String nokamarResult = result.getString("nokamar");

                txtnama.setText(namaResult);
                txtnim.setText(nimResult);
                pw.setText(passResult);
                txtjurusan.setText(jurusanResult);
                txtkamar.setText(nokamarResult);

                JOptionPane.showMessageDialog(null, "Data Mahasiswa "
                        + "" + namaResult + " ditemukan");

//                this.componentForm("cari");
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
//                kosongForm();
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtcarimhs.setText("");
    }//GEN-LAST:event_btcariActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new homeadmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        new menu_divisi().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new menuiqob().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new mahasantri().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed

        String nama = this.txtnama.getText();
        String nokamar = this.txtkamar.getText();
        String jurusan = this.txtjurusan.getText();
        String pass = this.pw.getText();
        String nim = this.txtnim.getText();

//        String kelasValue = ComboGrup.getSelection().getActionCommand();
        try {
            String sql = "UPDATE menumahasantri SET "
                    + " nama ='" + nama
                    + "', nokamar = '" + nokamar
                    + "', jurusan = '" + jurusan
                    + "', pass = '" + pass
                    + "' WHERE nim = '" + nim + "'";

            Connection conn = (Connection) conect.konekdb();
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update");

//            this.componentForm("edit");
//            kosongForm();
            tampilData();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Update");
            System.out.println(e);
        }
         txtnim.setText("");
        txtnama.setText("");
        pw.setText("");
        txtkamar.setText("");
        txtjurusan.setText("");
        txtcarimhs.setText("");
    }//GEN-LAST:event_bteditActionPerformed

    private void tabelMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMhsMouseClicked
        int row = tabelMhs.getSelectedRow();

        if (row > -1) {
            txtnim.setText(tabelMhs.getValueAt(row, 0).toString());
            txtnama.setText(tabelMhs.getValueAt(row, 1).toString());
            txtkamar.setText(tabelMhs.getValueAt(row, 2).toString());
            txtjurusan.setText(tabelMhs.getValueAt(row, 3).toString());

        }
    }//GEN-LAST:event_tabelMhsMouseClicked

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Yakin Mendelete record ini???", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            try {
                String del = "delete from menumahasantri where nim='" + txtnim.getText() + "'";
                PreparedStatement st = conect.konekdb().prepareStatement(del);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                tampilData();

//                this.componentForm("awal");
//            kosongForm();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
 txtnim.setText("");
        txtnama.setText("");
        pw.setText("");
        txtkamar.setText("");
        txtjurusan.setText("");
        txtcarimhs.setText("");
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        String nim = this.txtnim.getText();
        String nama = this.txtnama.getText();
        String pass = this.pw.getText();
        String nokamar = this.txtkamar.getText();
        String jurusan = this.txtjurusan.getText();

//        
        try {
            PreparedStatement gass = conect.konekdb().prepareStatement(""
                    + "INSERT INTO menumahasantri VALUES(?,?,?,?,?)");
            gass.setString(1, nim);
            gass.setString(2, pass);
            gass.setString(3, nama);
            gass.setString(4, nokamar);
            gass.setString(5, jurusan);

            gass.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            tampilData();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
 txtnim.setText("");
        txtnama.setText("");
        pw.setText("");
        txtkamar.setText("");
        txtjurusan.setText("");
        txtcarimhs.setText("");
    }//GEN-LAST:event_bttambahActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new loginadmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasantri().setVisible(true);
            }
        });
    }

    private void componentForm(String action) {
        switch (action) {
            case "nim":
                txtnim.setEnabled(false);

                break;

            default:
                return;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcari;
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pw;
    private javax.swing.JTable tabelMhs;
    private javax.swing.JTextField txtcarimhs;
    private javax.swing.JTextField txtjurusan;
    private javax.swing.JTextField txtkamar;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    // End of variables declaration//GEN-END:variables
}
